org: gianaedo
service: awsimplementation-reportes

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::866725828595:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_reportes

functions:
  crear:
    handler: user/CrearReporte.lambda_handler
    events:
      - http:
          path: /reporte/crear
          method: post
          cors: true
          integration: lambda

  listar:
    handler: admin/ListarReportes.lambda_handler
    events:
      - http:
          path: /reporte/listar
          method: get
          cors: true
          integration: lambda

  obtener:
    handler: admin/ObtenerReporte.lambda_handler
    events:
      - http:
          path: /reporte/{uuid}
          method: get
          cors: true
          integration: lambda

  eliminar:
    handler: admin/EliminarReporte.lambda_handler
    events:
      - http:
          path: /reporte/{uuid}
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    ReportesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
