org: gianaedo
service: awsimplementation-reportes

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::866725828595:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_reportes

functions:
  crear:
    handler: CrearReporte.lambda_handler
    events:
      - http:
          path: /reporte/crear
          method: post
          cors: true
          integration: lambda
    environment:
      CONNECTIONS_TABLE: Connections

  listar:
    handler: ListarReportes.lambda_handler
    events:
      - http:
          path: /reporte/listar
          method: get
          cors: true
          integration: lambda

  obtener:
    handler: ObtenerReporte.lambda_handler
    events:
      - http:
          path: /reporte/{uuid}
          method: get
          cors: true
          integration: lambda

  eliminar:
    handler: EliminarReporte.lambda_handler
    events:
      - http:
          path: /reporte/{uuid} 
          method: delete
          cors: true
          integration: lambda

  # WebSocket Lambda Functions
  connect:
    handler: connect.lambda_handler
    events:
      - websocket:
          route: $connect
    environment:
      CONNECTIONS_TABLE: Connections
      TABLE_NAME: ${self:provider.environment.TABLE_NAME}

  disconnect:
    handler: disconnect.lambda_handler
    events:
      - websocket:
          route: $disconnect
    environment:
      CONNECTIONS_TABLE: Connections

  default:
    handler: default.lambda_handler
    events:
      - websocket:
          route: $default
    environment:
      CONNECTIONS_TABLE: Connections
      TABLE_NAME: ${self:provider.environment.TABLE_NAME}

  # ========== AUTH LAMBDAS ==========
  registroUsuario:
    handler: RegistroUsuario.lambda_handler
    events:
      - http:
          path: /auth/registro/usuario
          method: post
          cors: true
          integration: lambda

  loginUsuario:
    handler: LoginUsuario.lambda_handler
    events:
      - http:
          path: /auth/login/usuario
          method: post
          cors: true
          integration: lambda

  registroAdmin:
    handler: RegistroAdmin.lambda_handler
    events:
      - http:
          path: /auth/registro/admin
          method: post
          cors: true
          integration: lambda

  loginAdmin:
    handler: LoginAdmin.lambda_handler
    events:
      - http:
          path: /auth/login/admin
          method: post
          cors: true
          integration: lambda

resources:
  Resources:

    #########################################
    # DynamoDB Tables
    #########################################
    ReportesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: uuid
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usuarios
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    AdminsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: admins
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
